name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Windows, Linux, MacOSX, HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: Scaling-Out
          preset: "CICD-${{ matrix.platform }}"
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CICD ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}